version: "2"
services:
  node:
    image: "abcdef:1.14"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
    expose:
      - "80"
      - "443"
    command: "pm2-runtime start ecosystem.config.js --only docker"
